# .gitlab-ci.yml  修正版 
pages:
  script:
    - rm -rf public               # 先清理旧目录 
    - mkdir public 
    - find . -maxdepth 1 -not -name 'public' -exec cp -r {} public/ \;  # 安全复制 
  artifacts:
    paths:
      - public 
  only:
    - master 