image: node:latest 
 
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g pnpm 
    - pnpm install 
    - pnpm build 
    - mv docs/.vitepress/dist public 
  artifacts:
    paths:
      - public 
  only:
    - master

